# https://docs.travis-ci.com/user/languages/javascript-with-nodejs/
language: node_js
node_js:
  - "node"
script: ./node_modules/.bin/karma start --browsers Firefox --single-run
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
